"""empty message

Revision ID: 70261549b0d0
Revises: 58a9adfb3025
Create Date: 2020-05-26 10:16:05.615531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70261549b0d0'
down_revision = '58a9adfb3025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_api_key_key', 'users', type_='unique')
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.create_unique_constraint('users_api_key_key', 'users', ['api_key'])
    # ### end Alembic commands ###
